In [1]:
import numpy as np
import gym

In [5]:
env = gym.make('Taxi-v3', render_mode="ansi")

In [7]:
env.reset()
print(env.render())

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+




In [11]:
Q = np.zeros((env.observation_space.n,env.action_space.n))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [12]:
alpha = 0.2
gamma = 0.99
epsilon = 1.0 
max_epsilon = 1.0 
min_epsilon = 0.01
decay_rate = 0.002
num_episodes = 40000
max_steps=100
rewards = []

In [15]:
# This cell is used to get to know what values does env.step(action) returns
action = env.action_space.sample()
print(action)
print(env.step(action))

0
(454, -1, False, False, {'prob': 1.0, 'action_mask': array([0, 1, 0, 1, 0, 0], dtype=int8)})


In [16]:
for episode in range(num_episodes):
    state, _ = env.reset()
    step = 0
    done = False
    epi_reward=0

    for step in range(max_steps):

        if np.random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state,:])

        new_state, reward, done, truncated, info = env.step(action)

        Q[state, action] = Q[state, action] + alpha * (reward + gamma * np.max(Q[new_state, :]) - Q[state, action])

        state = new_state
        epi_reward += reward

        if done == True: 
            break
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(epi_reward)

print(Q)
        

        

[[  0.           0.           0.           0.           0.
    0.        ]
 [  5.58336394   6.38381137   4.93807102   5.1701929    9.6220697
   -4.08646785]
 [  6.82631508  10.93074358   7.42314976   9.66857054  14.11880599
    1.42431572]
 ...
 [ -1.81753791  -1.79534923  -1.89318544  10.13666893  -9.67404462
  -10.61075952]
 [ -3.57892254   9.27198853  -3.57156717  -3.70595747 -10.98570409
  -12.2796812 ]
 [ -0.05760128   2.21942109   0.12671872  18.78280857  -1.80865134
   -3.2204736 ]]


***
Here we can see that the net rewards remain about the same after about 5 to 6 thousand episodes so we can also stop at that but I've done more episodes just to be sure

In [19]:
rewards_per_thousand= np.split(np.array(rewards), num_episodes/1000)
count = 1000
for r in rewards_per_thousand:
    print( count, ":", str(sum(r/10000)))
    count += 1000

1000 : -15.283599999999963
2000 : 0.34590000000000026
3000 : 0.6829000000000011
4000 : 0.7258000000000014
5000 : 0.7447000000000022
6000 : 0.7693000000000004
7000 : 0.7425000000000009
8000 : 0.7566000000000006
9000 : 0.7371000000000011
10000 : 0.7503000000000002
11000 : 0.7534000000000006
12000 : 0.7384000000000011
13000 : 0.7509000000000011
14000 : 0.7449000000000013
15000 : 0.7441000000000015
16000 : 0.7365000000000013
17000 : 0.7618000000000004
18000 : 0.7509000000000016
19000 : 0.7454000000000008
20000 : 0.7364000000000012
21000 : 0.7341999999999995
22000 : 0.7378000000000021
23000 : 0.7423000000000008
24000 : 0.746000000000001
25000 : 0.7428000000000016
26000 : 0.7676000000000017
27000 : 0.7466999999999997
28000 : 0.758000000000001
29000 : 0.7279000000000004
30000 : 0.7509000000000005
31000 : 0.7460000000000021
32000 : 0.7452000000000012
33000 : 0.7399000000000011
34000 : 0.752000000000001
35000 : 0.745100000000001
36000 : 0.743200000000002
37000 : 0.7251000000000029
38000 : 0.729

In [ ]:
env.reset()

for episode in range(3):
    state, _ = env.reset()
    step = 0
    done = False
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        action = np.argmax(Q[state,:])
        
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            print(env.render())
            # we can see if the last action displayed in the cell output is dropoff then we have succsessfully completed the task
        state = new_state
env.close()